version: '3.8'

services:
  psql-db:
    image: 'postgres:15.4'
    container_name: tap-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=*7&4%R4%3MQ%pe
      - POSTGRES_DB=tap_data
    ports:
      - '5432:5432'

  tap:
    container_name: tap_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tap-db-instance.cv4k0ue6sald.us-east-2.rds.amazonaws.com:5432/
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=*7&4%R4%3MQ%pe
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db